### PR TITLE
Auth Events Page While Logged In

### PR DESCRIPTION
**Pull request by psihanorak**
Events module displays while logged in.

### CODE REVIEW

**Review by luketlancaster — APPROVED** [review]
does this `buildLandingPage` function only get called when you're logged in? Or how does that logic work to only show the events button when logged in? Or what's the plan for that?

Code looks good, just curious about how that'll work

**Comment by psihanorak** [comment]
The Events module will not be accessible or be displayed while logged out.

**Comment by luketlancaster** [comment]
@psihanorak so you can click on this button, but there'll be logic down the line to not display anything for unauthenticated users?

**Comment by psihanorak** [comment]
Screen Shot 2020-07-28 at 9 31 43 AM

This is what is displayed when not logged in. *No events module displayed while logged out.

**Comment by psihanorak** [comment]
Screen Shot 2020-07-28 at 9 36 43 AM

@luketlancaster Displayed when logged in.

**Comment by luketlancaster** [comment]
🤔  I'm confused...what's keeping the events page from being printed all the time? I don't see any logic added in this PR...just some HTML in the domstring. Walk me through it

**Comment by psihanorak** [comment]
The events page will be hidden. I have a auth-logged out ticket that I am working on now.

**Pull request merged**
